services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TheLine\Lottie\:
        resource: '../Classes/*'

    TheLine\Lottie\Backend\DisplayConditions:
        public: true
