---
sniffs:
    -
        class: Indentation
        parameters:
            indentConditions: true
            indentPerLevel: 1
            useSpaces: false
    -
        class: DeadCode
    -
        class: OperatorWhitespace
    -
        class: RepeatingRValue
        disabled: true
    -
        class: DuplicateAssignment
    -
        class: EmptySection
        disabled: true
    -
        class: NestingConsistency
        parameters:
            commonPathPrefixThreshold: 3
